#ifndef GENERATED_ASN1SCC_drivers_config_H
#define GENERATED_ASN1SCC_drivers_config_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "samrh71-rtems-spw-driver.h"
#include "samrh71-rtems-serial-driver.h"
#include "samrh71-rtems-can-driver.h"

#ifdef  __cplusplus
extern "C" {
#endif



extern const Spw_SamRH71_Rtems_Conf_T pohidrv_node_1_spw0;
extern const Serial_SamRH71_Rtems_Conf_T pohidrv_node_1_uart0;
extern const CAN_SamRH71_Rtems_Conf_T pohidrv_node_1_can0;
extern const Spw_SamRH71_Rtems_Conf_T pohidrv_node_2_spw0;
extern const Serial_SamRH71_Rtems_Conf_T pohidrv_node_2_uart0;
extern const CAN_SamRH71_Rtems_Conf_T pohidrv_node_2_can0;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
