/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "drivers_config.h"

#ifdef __cplusplus
extern "C" {
#endif
const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_1 = {.devname = { [0 ... 19] = 0x20, [20] = 0x0}, .nodeaddr = 0UL, .corefreq = 0UL, .clockdiv = 0UL, .use_router = FALSE, .remove_prot_id = FALSE, .rxblock = FALSE, .txblock = FALSE, .exist = {.corefreq = 1, .clockdiv = 1, .use_router = 1, .remove_prot_id = 1, .rxblock = 1, .txblock = 1}};
const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_2 = {.devname = { [0 ... 19] = 0x20, [20] = 0x0}, .nodeaddr = 0UL, .corefreq = 0UL, .clockdiv = 0UL, .use_router = FALSE, .remove_prot_id = FALSE, .rxblock = FALSE, .txblock = FALSE, .exist = {.corefreq = 1, .clockdiv = 1, .use_router = 1, .remove_prot_id = 1, .rxblock = 1, .txblock = 1}};
#ifdef __cplusplus
}
#endif