/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "samrh71-rtems-spw-driver.h"
#include "samrh71-rtems-serial-driver.h"
#include "samrh71-rtems-can-driver.h"

#include "drivers_config.h"

const Spw_SamRH71_Rtems_Conf_T pohidrv_node_1_spw0 = {
    .link_id = spw0,
    .node_id = 32UL,
    .link_speed = b2Mbit,
    .remove_prot_id = FALSE,
    .exist = {
        .link_speed = 1,
        .remove_prot_id = 1
    }
};
const Serial_SamRH71_Rtems_Conf_T pohidrv_node_1_uart0 = {
    .devname = uart0,
    .speed = b38400,
    .parity = none,
    .packetizer_mode = {
        .kind = escaped_packets_PRESENT,
        .u = { .escaped_packets = TRUE}
    }
};
const CAN_SamRH71_Rtems_Conf_T pohidrv_node_1_can0 = {
    .can_interface = mcan_interface_mcan1,
    .bit_rate_prescaler = 0UL,
    .synchronization_jump = 2UL,
    .time_segments_after_sample_point = 2UL,
    .time_segments_before_sample_point = 15UL,
    .pck_source = pck_clock_source_plla_clock,
    .pck_prescaler = 14UL,
    .address = {
        .kind = can_samrh71_application_control_can_id_PRESENT,
        .u = { .can_samrh71_application_control_can_id = TRUE}
    },
    .exist = {
        .bit_rate_prescaler = 1,
        .synchronization_jump = 1,
        .time_segments_after_sample_point = 1,
        .time_segments_before_sample_point = 1,
        .pck_source = 1,
        .pck_prescaler = 1
    }
};
const Spw_SamRH71_Rtems_Conf_T pohidrv_node_2_spw0 = {
    .link_id = spw0,
    .node_id = 32UL,
    .link_speed = b2Mbit,
    .remove_prot_id = FALSE,
    .exist = {
        .link_speed = 1,
        .remove_prot_id = 1
    }
};
const Serial_SamRH71_Rtems_Conf_T pohidrv_node_2_uart0 = {
    .devname = uart0,
    .speed = b38400,
    .parity = none,
    .packetizer_mode = {
        .kind = escaped_packets_PRESENT,
        .u = { .escaped_packets = TRUE}
    }
};
const CAN_SamRH71_Rtems_Conf_T pohidrv_node_2_can0 = {
    .can_interface = mcan_interface_mcan1,
    .bit_rate_prescaler = 0UL,
    .synchronization_jump = 2UL,
    .time_segments_after_sample_point = 2UL,
    .time_segments_before_sample_point = 15UL,
    .pck_source = pck_clock_source_plla_clock,
    .pck_prescaler = 14UL,
    .address = {
        .kind = can_samrh71_application_control_can_id_PRESENT,
        .u = { .can_samrh71_application_control_can_id = TRUE}
    },
    .exist = {
        .bit_rate_prescaler = 1,
        .synchronization_jump = 1,
        .time_segments_after_sample_point = 1,
        .time_segments_before_sample_point = 1,
        .pck_source = 1,
        .pck_prescaler = 1
    }
};

