#ifndef GENERATED_ASN1SCC_drivers_config_H
#define GENERATED_ASN1SCC_drivers_config_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "samrh71-rtems-spw-driver.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_1;
extern const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_2;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

#ifdef __cplusplus
}

#endif

#endif
