/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "drivers_config.h"

#ifdef __cplusplus
extern "C" {
#endif
const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_1 = {
	.link_name = Spw_SamRH71_Rtems_Conf_Link_T_spw0,
	.destination_link = Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0,
	.link_speed = 0UL,
	.remove_prot_id = FALSE,
	.exist = { .link_speed = 1, .remove_prot_id = 1 }
};
const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Confg_port_2 = {
	.link_name = Spw_SamRH71_Rtems_Conf_Link_T_spw1,
	.destination_link = Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0,
	.link_speed = 0UL,
	.remove_prot_id = FALSE,
	.exist = { .link_speed = 1, .remove_prot_id = 1 }
};
#ifdef __cplusplus
}
#endif