#ifndef GENERATED_ASN1SCC_samrh71_rtems_can_driver_H
#define GENERATED_ASN1SCC_samrh71_rtems_can_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef enum {
    mcan_interface_mcan0 = 0,
    mcan_interface_mcan1 = 1
} CAN_Samrh71_Rtems_Interface_T;

// please use the following macros to avoid breaking code.
#define CAN_Samrh71_Rtems_Interface_T_mcan_interface_mcan0 mcan_interface_mcan0
#define CAN_Samrh71_Rtems_Interface_T_mcan_interface_mcan1 mcan_interface_mcan1

#define ERR_CAN_SAMRH71_RTEMS_INTERFACE_T		1  /*mcan-interface-mcan0 | mcan-interface-mcan1*/
flag CAN_Samrh71_Rtems_Interface_T_IsConstraintValid(const CAN_Samrh71_Rtems_Interface_T* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Interface_T_Initialize(CAN_Samrh71_Rtems_Interface_T* pVal);
typedef enum {
    pck_clock_source_main_clock = 0,
    pck_clock_source_plla_clock = 1,
    pck_clock_source_pllb_clock = 2,
    pck_clock_source_master_clock = 3,
    pck_clock_source_rc2_clock = 4
} CAN_Samrh71_Rtems_PCK_Clock_Source;

// please use the following macros to avoid breaking code.
#define CAN_Samrh71_Rtems_PCK_Clock_Source_pck_clock_source_main_clock pck_clock_source_main_clock
#define CAN_Samrh71_Rtems_PCK_Clock_Source_pck_clock_source_plla_clock pck_clock_source_plla_clock
#define CAN_Samrh71_Rtems_PCK_Clock_Source_pck_clock_source_pllb_clock pck_clock_source_pllb_clock
#define CAN_Samrh71_Rtems_PCK_Clock_Source_pck_clock_source_master_clock pck_clock_source_master_clock
#define CAN_Samrh71_Rtems_PCK_Clock_Source_pck_clock_source_rc2_clock pck_clock_source_rc2_clock

#define ERR_CAN_SAMRH71_RTEMS_PCK_CLOCK_SOURCE		6  /*pck-clock-source-main-clock | pck-clock-source-plla-clock | pck-clock-source-pllb-clock | pck-clock-source-master-clock | pck-clock-source-rc2-clock*/
flag CAN_Samrh71_Rtems_PCK_Clock_Source_IsConstraintValid(const CAN_Samrh71_Rtems_PCK_Clock_Source* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_PCK_Clock_Source_Initialize(CAN_Samrh71_Rtems_PCK_Clock_Source* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_PCK_Prescaler;


#define ERR_CAN_SAMRH71_RTEMS_PCK_PRESCALER		11  /*(0 .. 255)*/
flag CAN_Samrh71_Rtems_PCK_Prescaler_IsConstraintValid(const CAN_Samrh71_Rtems_PCK_Prescaler* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_PCK_Prescaler_Initialize(CAN_Samrh71_Rtems_PCK_Prescaler* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width;


#define ERR_CAN_SAMRH71_RTEMS_DATA_SYNCHRONIZATION_JUMP_WIDTH		16  /*(0 .. 7)*/
flag CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width_IsConstraintValid(const CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width_Initialize(CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point;


#define ERR_CAN_SAMRH71_RTEMS_DATA_TIME_SEGMENT_BEFORE_SAMPLE_POINT		21  /*(1 .. 31)*/
flag CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point_IsConstraintValid(const CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point_Initialize(CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point;


#define ERR_CAN_SAMRH71_RTEMS_DATA_TIME_SEGMENT_AFTER_SAMPLE_POINT		26  /*(0 .. 15)*/
flag CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point_IsConstraintValid(const CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point_Initialize(CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler;


#define ERR_CAN_SAMRH71_RTEMS_DATA_BIT_RATE_PRESCALER		31  /*(0 .. 31)*/
flag CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler_IsConstraintValid(const CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler_Initialize(CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Standard_Can_Id;


#define ERR_CAN_SAMRH71_RTEMS_STANDARD_CAN_ID		36  /*(0 .. 2047)*/
flag CAN_Samrh71_Rtems_Standard_Can_Id_IsConstraintValid(const CAN_Samrh71_Rtems_Standard_Can_Id* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Standard_Can_Id_Initialize(CAN_Samrh71_Rtems_Standard_Can_Id* pVal);
typedef asn1SccUint CAN_Samrh71_Rtems_Extended_Can_Id;


#define ERR_CAN_SAMRH71_RTEMS_EXTENDED_CAN_ID		41  /*(0 .. 536870911)*/
flag CAN_Samrh71_Rtems_Extended_Can_Id_IsConstraintValid(const CAN_Samrh71_Rtems_Extended_Can_Id* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Extended_Can_Id_Initialize(CAN_Samrh71_Rtems_Extended_Can_Id* pVal);
/*-- CAN_Samrh71_Rtems_Can_Id --------------------------------------------*/

typedef enum {
    CAN_Samrh71_Rtems_Can_Id_NONE,
    can_samrh71_can_id_standard_PRESENT,
    can_samrh71_can_id_extended_PRESENT
} CAN_Samrh71_Rtems_Can_Id_selection;

typedef union {
    CAN_Samrh71_Rtems_Standard_Can_Id can_samrh71_can_id_standard;
    CAN_Samrh71_Rtems_Extended_Can_Id can_samrh71_can_id_extended;
} CAN_Samrh71_Rtems_Can_Id_unchecked_union;

typedef struct {
    CAN_Samrh71_Rtems_Can_Id_selection kind;

    CAN_Samrh71_Rtems_Can_Id_unchecked_union u;
} CAN_Samrh71_Rtems_Can_Id;

#define ERR_CAN_SAMRH71_RTEMS_CAN_ID		66  /**/
#define ERR_CAN_SAMRH71_RTEMS_CAN_ID_CAN_SAMRH71_CAN_ID_STANDARD_2		51  /**/
#define ERR_CAN_SAMRH71_RTEMS_CAN_ID_CAN_SAMRH71_CAN_ID_EXTENDED_2		61  /**/
flag CAN_Samrh71_Rtems_Can_Id_IsConstraintValid(const CAN_Samrh71_Rtems_Can_Id* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Can_Id_Initialize(CAN_Samrh71_Rtems_Can_Id* pVal);
typedef flag CAN_Samrh71_Rtems_Dummy;


#define ERR_CAN_SAMRH71_RTEMS_DUMMY		71  /**/
flag CAN_Samrh71_Rtems_Dummy_IsConstraintValid(const CAN_Samrh71_Rtems_Dummy* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Dummy_Initialize(CAN_Samrh71_Rtems_Dummy* pVal);
/*-- CAN_Samrh71_Rtems_Address --------------------------------------------*/

typedef enum {
    CAN_Samrh71_Rtems_Address_NONE,
    can_samrh71_static_can_id_PRESENT,
    can_samrh71_application_control_can_id_PRESENT
} CAN_Samrh71_Rtems_Address_selection;

typedef union {
    CAN_Samrh71_Rtems_Can_Id can_samrh71_static_can_id;
    CAN_Samrh71_Rtems_Dummy can_samrh71_application_control_can_id;
} CAN_Samrh71_Rtems_Address_unchecked_union;

typedef struct {
    CAN_Samrh71_Rtems_Address_selection kind;

    CAN_Samrh71_Rtems_Address_unchecked_union u;
} CAN_Samrh71_Rtems_Address;

#define ERR_CAN_SAMRH71_RTEMS_ADDRESS		91  /**/
#define ERR_CAN_SAMRH71_RTEMS_ADDRESS_CAN_SAMRH71_STATIC_CAN_ID		76  /**/
#define ERR_CAN_SAMRH71_RTEMS_ADDRESS_CAN_SAMRH71_APPLICATION_CONTROL_CAN_ID_2		86  /**/
flag CAN_Samrh71_Rtems_Address_IsConstraintValid(const CAN_Samrh71_Rtems_Address* pVal, int* pErrCode);

void CAN_Samrh71_Rtems_Address_Initialize(CAN_Samrh71_Rtems_Address* pVal);
/*-- CAN_SamRH71_Rtems_Conf_T --------------------------------------------*/
typedef struct {
    unsigned long bit_rate_prescaler:1;
    unsigned long synchronization_jump:1;
    unsigned long time_segments_after_sample_point:1;
    unsigned long time_segments_before_sample_point:1;
    unsigned long pck_source:1;
    unsigned long pck_prescaler:1;
} CAN_SamRH71_Rtems_Conf_T_exist;
typedef struct {
    CAN_Samrh71_Rtems_Interface_T can_interface;
    CAN_Samrh71_Rtems_Data_Bit_Rate_Prescaler bit_rate_prescaler;
    CAN_Samrh71_Rtems_Data_Synchronization_Jump_Width synchronization_jump;
    CAN_Samrh71_Rtems_Data_Time_Segment_After_Sample_Point time_segments_after_sample_point;
    CAN_Samrh71_Rtems_Data_Time_Segment_Before_Sample_Point time_segments_before_sample_point;
    CAN_Samrh71_Rtems_PCK_Clock_Source pck_source;
    CAN_Samrh71_Rtems_PCK_Prescaler pck_prescaler;
    CAN_Samrh71_Rtems_Address address;

    CAN_SamRH71_Rtems_Conf_T_exist exist;

} CAN_SamRH71_Rtems_Conf_T;

#define ERR_CAN_SAMRH71_RTEMS_CONF_T		171  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_CAN_INTERFACE_2		101  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_BIT_RATE_PRESCALER_2		111  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_SYNCHRONIZATION_JUMP_2		121  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_TIME_SEGMENTS_AFTER_SAMPLE_POINT_2		131  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_TIME_SEGMENTS_BEFORE_SAMPLE_POINT_2		141  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_PCK_SOURCE_2		151  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_PCK_PRESCALER_2		161  /**/
#define ERR_CAN_SAMRH71_RTEMS_CONF_T_ADDRESS		166  /**/
flag CAN_SamRH71_Rtems_Conf_T_IsConstraintValid(const CAN_SamRH71_Rtems_Conf_T* pVal, int* pErrCode);

void CAN_SamRH71_Rtems_Conf_T_Initialize(CAN_SamRH71_Rtems_Conf_T* pVal);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
