#ifndef GENERATED_ASN1SCC_samrh71_rtems_spw_driver_H
#define GENERATED_ASN1SCC_samrh71_rtems_spw_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	Spw_SamRH71_Rtems_Conf_Link_T_spw0 = 0,
	Spw_SamRH71_Rtems_Conf_Link_T_spw1 = 1
} Spw_SamRH71_Rtems_Conf_Link_T;

// please use the following macros to avoid breaking code.
#define Spw_SamRH71_Rtems_Conf_Link_T_spw0 Spw_SamRH71_Rtems_Conf_Link_T_spw0
#define Spw_SamRH71_Rtems_Conf_Link_T_spw1 Spw_SamRH71_Rtems_Conf_Link_T_spw1

#define ERR_SPW_SAMRH71_RTEMS_CONF_LINK_T 1 /*spw0 | spw1*/
flag Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Link_T *pVal, int *pErrCode);

#ifdef __cplusplus
extern const Spw_SamRH71_Rtems_Conf_Link_T
	Spw_SamRH71_Rtems_Conf_Link_T_constant;
#else
#define Spw_SamRH71_Rtems_Conf_Link_T_constant \
	Spw_SamRH71_Rtems_Conf_Link_T_spw0
#endif

void Spw_SamRH71_Rtems_Conf_Link_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Link_T *pVal);
typedef enum {
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0 = 0,
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw1 = 1
} Spw_SamRH71_Rtems_Conf_Destination_Link_T;

// please use the following macros to avoid breaking code.
#define Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0 \
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0
#define Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw1 \
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw1

#define ERR_SPW_SAMRH71_RTEMS_CONF_DESTINATION_LINK_T 6 /*spw0 | spw1*/
flag Spw_SamRH71_Rtems_Conf_Destination_Link_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Destination_Link_T *pVal, int *pErrCode);

#ifdef __cplusplus
extern const Spw_SamRH71_Rtems_Conf_Destination_Link_T
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_constant;
#else
#define Spw_SamRH71_Rtems_Conf_Destination_Link_T_constant \
	Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0
#endif

void Spw_SamRH71_Rtems_Conf_Destination_Link_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Destination_Link_T *pVal);
typedef asn1SccUint Spw_SamRH71_Rtems_Conf_Link_Speed_T;

#define ERR_SPW_SAMRH71_RTEMS_CONF_LINK_SPEED_T 11 /*(0 .. 4294967295)*/
flag Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Link_Speed_T *pVal, int *pErrCode);

#ifdef __cplusplus
extern const Spw_SamRH71_Rtems_Conf_Link_Speed_T
	Spw_SamRH71_Rtems_Conf_Link_Speed_T_constant;
#else
#define Spw_SamRH71_Rtems_Conf_Link_Speed_T_constant 0UL
#endif

void Spw_SamRH71_Rtems_Conf_Link_Speed_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Link_Speed_T *pVal);
/*-- Spw_SamRH71_Rtems_Conf_T --------------------------------------------*/
typedef struct {
	unsigned long link_speed : 1;
	unsigned long remove_prot_id : 1;
} Spw_SamRH71_Rtems_Conf_T_exist;
typedef struct {
	Spw_SamRH71_Rtems_Conf_Link_T link_name;
	Spw_SamRH71_Rtems_Conf_Destination_Link_T destination_link;
	Spw_SamRH71_Rtems_Conf_Link_Speed_T link_speed;
	flag remove_prot_id;

	Spw_SamRH71_Rtems_Conf_T_exist exist;

} Spw_SamRH71_Rtems_Conf_T;

#define ERR_SPW_SAMRH71_RTEMS_CONF_T 51 /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_LINK_NAME_2 21 /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_DESTINATION_LINK_2 31 /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_LINK_SPEED_2 41 /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_REMOVE_PROT_ID 46 /**/
flag Spw_SamRH71_Rtems_Conf_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_T *pVal, int *pErrCode);

#ifdef __cplusplus
extern const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Conf_T_constant;
#else
#define Spw_SamRH71_Rtems_Conf_T_constant                                     \
	{ .link_name = Spw_SamRH71_Rtems_Conf_Link_T_spw0,                    \
	  .destination_link = Spw_SamRH71_Rtems_Conf_Destination_Link_T_spw0, \
	  .link_speed = 0UL,                                                  \
	  .remove_prot_id = FALSE,                                            \
	  .exist = { .link_speed = 1, .remove_prot_id = 1 } }
#endif

void Spw_SamRH71_Rtems_Conf_T_Initialize(Spw_SamRH71_Rtems_Conf_T *pVal);

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

#ifdef __cplusplus
}

#endif

#endif
