#ifndef GENERATED_ASN1SCC_samrh71_rtems_serial_driver_H
#define GENERATED_ASN1SCC_samrh71_rtems_serial_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	uart0 = 0,
	uart1 = 1,
	uart2 = 2,
	uart3 = 3,
	uart4 = 4,
	uart5 = 5,
	uart6 = 6,
	uart7 = 7,
	uart8 = 8,
	uart9 = 9
} Serial_SamRH71_Rtems_Device_T;

// please use the following macros to avoid breaking code.
#define Serial_SamRH71_Rtems_Device_T_uart0 uart0
#define Serial_SamRH71_Rtems_Device_T_uart1 uart1
#define Serial_SamRH71_Rtems_Device_T_uart2 uart2
#define Serial_SamRH71_Rtems_Device_T_uart3 uart3
#define Serial_SamRH71_Rtems_Device_T_uart4 uart4
#define Serial_SamRH71_Rtems_Device_T_uart5 uart5
#define Serial_SamRH71_Rtems_Device_T_uart6 uart6
#define Serial_SamRH71_Rtems_Device_T_uart7 uart7
#define Serial_SamRH71_Rtems_Device_T_uart8 uart8
#define Serial_SamRH71_Rtems_Device_T_uart9 uart9

#define ERR_SERIAL_SAMRH71_RTEMS_DEVICE_T \
	176 /*uart0 | uart1 | uart2 | uart3 | uart4 | uart5 | uart6 | uart7 | uart8 | uart9*/
flag Serial_SamRH71_Rtems_Device_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Device_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Device_T_Initialize(
	Serial_SamRH71_Rtems_Device_T *pVal);
typedef enum {
	b9600 = 0,
	b19200 = 1,
	b38400 = 2,
	b57600 = 3,
	b115200 = 4,
	b230400 = 5
} Serial_SamRH71_Rtems_Baudrate_T;

// please use the following macros to avoid breaking code.
#define Serial_SamRH71_Rtems_Baudrate_T_b9600 b9600
#define Serial_SamRH71_Rtems_Baudrate_T_b19200 b19200
#define Serial_SamRH71_Rtems_Baudrate_T_b38400 b38400
#define Serial_SamRH71_Rtems_Baudrate_T_b57600 b57600
#define Serial_SamRH71_Rtems_Baudrate_T_b115200 b115200
#define Serial_SamRH71_Rtems_Baudrate_T_b230400 b230400

#define ERR_SERIAL_SAMRH71_RTEMS_BAUDRATE_T \
	181 /*b9600 | b19200 | b38400 | b57600 | b115200 | b230400*/
flag Serial_SamRH71_Rtems_Baudrate_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Baudrate_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Baudrate_T_Initialize(
	Serial_SamRH71_Rtems_Baudrate_T *pVal);
typedef enum { even = 0, odd = 1, none = 2 } Serial_SamRH71_Rtems_Parity_T;

// please use the following macros to avoid breaking code.
#define Serial_SamRH71_Rtems_Parity_T_even even
#define Serial_SamRH71_Rtems_Parity_T_odd odd
#define Serial_SamRH71_Rtems_Parity_T_none none

#define ERR_SERIAL_SAMRH71_RTEMS_PARITY_T 186 /*even | odd | none*/
flag Serial_SamRH71_Rtems_Parity_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Parity_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Parity_T_Initialize(
	Serial_SamRH71_Rtems_Parity_T *pVal);
typedef asn1SccUint Serial_SamRH71_Escape_Byte_T;

#define ERR_SERIAL_SAMRH71_ESCAPE_BYTE_T 191 /*(0..255)*/
flag Serial_SamRH71_Escape_Byte_T_IsConstraintValid(
	const Serial_SamRH71_Escape_Byte_T *pVal, int *pErrCode);

void Serial_SamRH71_Escape_Byte_T_Initialize(Serial_SamRH71_Escape_Byte_T *pVal);
typedef flag Serial_SamRH71_Rtems_Dummy;

#define ERR_SERIAL_SAMRH71_RTEMS_DUMMY 196 /**/
flag Serial_SamRH71_Rtems_Dummy_IsConstraintValid(
	const Serial_SamRH71_Rtems_Dummy *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Dummy_Initialize(Serial_SamRH71_Rtems_Dummy *pVal);
/*-- Serial_SamRH71_Rtems_Packetizer_Mode_T --------------------------------------------*/
/*-- Serial_SamRH71_Rtems_Packetizer_Mode_T_raw --------------------------------------------*/

typedef enum {
	Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_NONE,
	single_byte_PRESENT,
	custom_escape_byte_PRESENT
} Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_selection;

typedef union {
	Serial_SamRH71_Rtems_Dummy single_byte;
	Serial_SamRH71_Escape_Byte_T custom_escape_byte;
} Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_unchecked_union;

typedef struct {
	Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_selection kind;

	Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_unchecked_union u;
} Serial_SamRH71_Rtems_Packetizer_Mode_T_raw;

typedef enum {
	Serial_SamRH71_Rtems_Packetizer_Mode_T_NONE,
	escaped_packets_PRESENT,
	raw_PRESENT
} Serial_SamRH71_Rtems_Packetizer_Mode_T_selection;

typedef union {
	flag escaped_packets;
	Serial_SamRH71_Rtems_Packetizer_Mode_T_raw raw;
} Serial_SamRH71_Rtems_Packetizer_Mode_T_unchecked_union;

typedef struct {
	Serial_SamRH71_Rtems_Packetizer_Mode_T_selection kind;

	Serial_SamRH71_Rtems_Packetizer_Mode_T_unchecked_union u;
} Serial_SamRH71_Rtems_Packetizer_Mode_T;

#define ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T_RAW 226 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T_RAW_SINGLE_BYTE_2 211 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T_RAW_CUSTOM_ESCAPE_BYTE_2 \
	221 /**/
flag Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_IsConstraintValid(
	const Serial_SamRH71_Rtems_Packetizer_Mode_T_raw *pVal, int *pErrCode);

#define ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T 231 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T_ESCAPED_PACKETS 201 /**/
flag Serial_SamRH71_Rtems_Packetizer_Mode_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Packetizer_Mode_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_Initialize(
	Serial_SamRH71_Rtems_Packetizer_Mode_T_raw *pVal);
void Serial_SamRH71_Rtems_Packetizer_Mode_T_Initialize(
	Serial_SamRH71_Rtems_Packetizer_Mode_T *pVal);
typedef enum { asynchronous = 0, blocking = 1 } Serial_SamRH71_Rtems_Tx_Mode_T;

// please use the following macros to avoid breaking code.
#define Serial_SamRH71_Rtems_Tx_Mode_T_asynchronous asynchronous
#define Serial_SamRH71_Rtems_Tx_Mode_T_blocking blocking

#define ERR_SERIAL_SAMRH71_RTEMS_TX_MODE_T 236 /*asynchronous | blocking*/
flag Serial_SamRH71_Rtems_Tx_Mode_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Tx_Mode_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Tx_Mode_T_Initialize(
	Serial_SamRH71_Rtems_Tx_Mode_T *pVal);
/*-- Serial_SamRH71_Rtems_Conf_T --------------------------------------------*/
typedef struct {
	Serial_SamRH71_Rtems_Device_T devname;
	Serial_SamRH71_Rtems_Baudrate_T speed;
	Serial_SamRH71_Rtems_Parity_T parity;
	Serial_SamRH71_Rtems_Packetizer_Mode_T packetizer_mode;
	Serial_SamRH71_Rtems_Tx_Mode_T tx_mode;

} Serial_SamRH71_Rtems_Conf_T;

#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T 286 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T_DEVNAME_2 246 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T_SPEED_2 256 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T_PARITY_2 266 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T_PACKETIZER_MODE 271 /**/
#define ERR_SERIAL_SAMRH71_RTEMS_CONF_T_TX_MODE_2 281 /**/
flag Serial_SamRH71_Rtems_Conf_T_IsConstraintValid(
	const Serial_SamRH71_Rtems_Conf_T *pVal, int *pErrCode);

void Serial_SamRH71_Rtems_Conf_T_Initialize(Serial_SamRH71_Rtems_Conf_T *pVal);

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

#ifdef __cplusplus
}

#endif

#endif
