/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "samrh71-rtems-serial-driver.h"


flag Serial_SamRH71_Rtems_Device_T_IsConstraintValid(const Serial_SamRH71_Rtems_Device_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((((((((((*(pVal)) == uart0)) || (((*(pVal)) == uart1)))) || (((*(pVal)) == uart2)))) || (((*(pVal)) == uart3)))) || (((*(pVal)) == uart4)))) || (((*(pVal)) == uart5)))) || (((*(pVal)) == uart6)))) || (((*(pVal)) == uart7)))) || (((*(pVal)) == uart8)))) || (((*(pVal)) == uart9)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMRH71_RTEMS_DEVICE_T;

	return ret;
}

void Serial_SamRH71_Rtems_Device_T_Initialize(Serial_SamRH71_Rtems_Device_T* pVal)
{
	(void)pVal;


	(*(pVal)) = uart0;
}


flag Serial_SamRH71_Rtems_Baudrate_T_IsConstraintValid(const Serial_SamRH71_Rtems_Baudrate_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((*(pVal)) == b9600)) || (((*(pVal)) == b19200)))) || (((*(pVal)) == b38400)))) || (((*(pVal)) == b57600)))) || (((*(pVal)) == b115200)))) || (((*(pVal)) == b230400)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMRH71_RTEMS_BAUDRATE_T;

	return ret;
}

void Serial_SamRH71_Rtems_Baudrate_T_Initialize(Serial_SamRH71_Rtems_Baudrate_T* pVal)
{
	(void)pVal;


	(*(pVal)) = b9600;
}


flag Serial_SamRH71_Rtems_Parity_T_IsConstraintValid(const Serial_SamRH71_Rtems_Parity_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((*(pVal)) == even)) || (((*(pVal)) == odd)))) || (((*(pVal)) == none)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMRH71_RTEMS_PARITY_T;

	return ret;
}

void Serial_SamRH71_Rtems_Parity_T_Initialize(Serial_SamRH71_Rtems_Parity_T* pVal)
{
	(void)pVal;


	(*(pVal)) = even;
}


flag Serial_SamRH71_Escape_Byte_T_IsConstraintValid(const Serial_SamRH71_Escape_Byte_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMRH71_ESCAPE_BYTE_T;

	return ret;
}

void Serial_SamRH71_Escape_Byte_T_Initialize(Serial_SamRH71_Escape_Byte_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag Serial_SamRH71_Rtems_Dummy_IsConstraintValid(const Serial_SamRH71_Rtems_Dummy* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void Serial_SamRH71_Rtems_Dummy_Initialize(Serial_SamRH71_Rtems_Dummy* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}


flag Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_IsConstraintValid(const Serial_SamRH71_Rtems_Packetizer_Mode_T_raw* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case single_byte_PRESENT : 
            ret = Serial_SamRH71_Rtems_Dummy_IsConstraintValid((&(pVal->u.single_byte)), pErrCode);
            break;          
        case custom_escape_byte_PRESENT : 
            ret = Serial_SamRH71_Escape_Byte_T_IsConstraintValid((&(pVal->u.custom_escape_byte)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T_RAW;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

flag Serial_SamRH71_Rtems_Packetizer_Mode_T_IsConstraintValid(const Serial_SamRH71_Rtems_Packetizer_Mode_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case escaped_packets_PRESENT : /*COVERAGE_IGNORE*/
            ret = TRUE;
            *pErrCode = 0;
            break;          /*COVERAGE_IGNORE*/
        case raw_PRESENT : 
            ret = Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_IsConstraintValid((&(pVal->u.raw)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_SERIAL_SAMRH71_RTEMS_PACKETIZER_MODE_T;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void Serial_SamRH71_Rtems_Packetizer_Mode_T_raw_Initialize(Serial_SamRH71_Rtems_Packetizer_Mode_T_raw* pVal)
{
	(void)pVal;


	pVal->kind = single_byte_PRESENT;
	pVal->u.single_byte = FALSE;
}
void Serial_SamRH71_Rtems_Packetizer_Mode_T_Initialize(Serial_SamRH71_Rtems_Packetizer_Mode_T* pVal)
{
	(void)pVal;


	pVal->kind = escaped_packets_PRESENT;
	pVal->u.escaped_packets = FALSE;
}


flag Serial_SamRH71_Rtems_Conf_T_IsConstraintValid(const Serial_SamRH71_Rtems_Conf_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamRH71_Rtems_Device_T_IsConstraintValid((&(pVal->devname)), pErrCode);
    if (ret) {
        ret = Serial_SamRH71_Rtems_Baudrate_T_IsConstraintValid((&(pVal->speed)), pErrCode);
        if (ret) {
            ret = Serial_SamRH71_Rtems_Parity_T_IsConstraintValid((&(pVal->parity)), pErrCode);
            if (ret) {
                ret = Serial_SamRH71_Rtems_Packetizer_Mode_T_IsConstraintValid((&(pVal->packetizer_mode)), pErrCode);
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Serial_SamRH71_Rtems_Conf_T_Initialize(Serial_SamRH71_Rtems_Conf_T* pVal)
{
	(void)pVal;


	/*set devname */
	Serial_SamRH71_Rtems_Device_T_Initialize((&(pVal->devname)));
	/*set speed */
	Serial_SamRH71_Rtems_Baudrate_T_Initialize((&(pVal->speed)));
	/*set parity */
	Serial_SamRH71_Rtems_Parity_T_Initialize((&(pVal->parity)));
	/*set packetizer_mode */
	Serial_SamRH71_Rtems_Packetizer_Mode_T_Initialize((&(pVal->packetizer_mode)));
}


