/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "samrh71-rtems-spw-driver.h"


flag Spw_SamRH71_Rtems_Conf_Core_Frequence_T_Equal(const Spw_SamRH71_Rtems_Conf_Core_Frequence_T* pVal1, const Spw_SamRH71_Rtems_Conf_Core_Frequence_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag Spw_SamRH71_Rtems_Conf_Core_Frequence_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Core_Frequence_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_CORE_FREQUENCE_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Core_Frequence_T_Initialize(Spw_SamRH71_Rtems_Conf_Core_Frequence_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag Spw_SamRH71_Rtems_Conf_Node_Addr_T_Equal(const Spw_SamRH71_Rtems_Conf_Node_Addr_T* pVal1, const Spw_SamRH71_Rtems_Conf_Node_Addr_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag Spw_SamRH71_Rtems_Conf_Node_Addr_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Node_Addr_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_NODE_ADDR_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Node_Addr_T_Initialize(Spw_SamRH71_Rtems_Conf_Node_Addr_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag Spw_SamRH71_Rtems_Conf_Clock_Division_T_Equal(const Spw_SamRH71_Rtems_Conf_Clock_Division_T* pVal1, const Spw_SamRH71_Rtems_Conf_Clock_Division_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag Spw_SamRH71_Rtems_Conf_Clock_Division_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Clock_Division_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_CLOCK_DIVISION_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Clock_Division_T_Initialize(Spw_SamRH71_Rtems_Conf_Clock_Division_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag Spw_SamRH71_Rtems_Conf_T_devname_Equal(const Spw_SamRH71_Rtems_Conf_T_devname pVal1, const Spw_SamRH71_Rtems_Conf_T_devname pVal2)
{
	return strcmp(pVal1, pVal2) == 0;

}

flag Spw_SamRH71_Rtems_Conf_T_Equal(const Spw_SamRH71_Rtems_Conf_T* pVal1, const Spw_SamRH71_Rtems_Conf_T* pVal2)
{
	flag ret=TRUE;

    ret = Spw_SamRH71_Rtems_Conf_T_devname_Equal(pVal1->devname, pVal2->devname);

    if (ret) {
        ret = (pVal1->nodeaddr == pVal2->nodeaddr);

        if (ret) {
            ret = (pVal1->exist.corefreq == pVal2->exist.corefreq);
            if (ret && pVal1->exist.corefreq) {
            	ret = (pVal1->corefreq == pVal2->corefreq);
            }

            if (ret) {
                ret = (pVal1->exist.clockdiv == pVal2->exist.clockdiv);
                if (ret && pVal1->exist.clockdiv) {
                	ret = (pVal1->clockdiv == pVal2->clockdiv);
                }

                if (ret) {
                    ret = (pVal1->exist.use_router == pVal2->exist.use_router);
                    if (ret && pVal1->exist.use_router) {
                    	ret = (pVal1->use_router == pVal2->use_router);
                    }

                    if (ret) {
                        ret = (pVal1->exist.remove_prot_id == pVal2->exist.remove_prot_id);
                        if (ret && pVal1->exist.remove_prot_id) {
                        	ret = (pVal1->remove_prot_id == pVal2->remove_prot_id);
                        }

                        if (ret) {
                            ret = (pVal1->exist.rxblock == pVal2->exist.rxblock);
                            if (ret && pVal1->exist.rxblock) {
                            	ret = (pVal1->rxblock == pVal2->rxblock);
                            }

                            if (ret) {
                                ret = (pVal1->exist.txblock == pVal2->exist.txblock);
                                if (ret && pVal1->exist.txblock) {
                                	ret = (pVal1->txblock == pVal2->txblock);
                                }

                            }

                        }

                    }

                }

            }

        }

    }

	return ret;

}

flag Spw_SamRH71_Rtems_Conf_T_devname_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_T_devname pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= strlen(pVal)) && (strlen(pVal) <= 20));
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_T_DEVNAME;

	return ret;
}

flag Spw_SamRH71_Rtems_Conf_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Spw_SamRH71_Rtems_Conf_T_devname_IsConstraintValid(pVal->devname, pErrCode);
    if (ret) {
        ret = Spw_SamRH71_Rtems_Conf_Node_Addr_T_IsConstraintValid((&(pVal->nodeaddr)), pErrCode);
        if (ret) {
            if (pVal->exist.corefreq) {
            	ret = Spw_SamRH71_Rtems_Conf_Core_Frequence_T_IsConstraintValid((&(pVal->corefreq)), pErrCode);
            }
            if (ret) {
                if (pVal->exist.clockdiv) {
                	ret = Spw_SamRH71_Rtems_Conf_Clock_Division_T_IsConstraintValid((&(pVal->clockdiv)), pErrCode);
                }
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Spw_SamRH71_Rtems_Conf_T_devname_Initialize(Spw_SamRH71_Rtems_Conf_T_devname pVal)
{
	(void)pVal;


	memset(pVal, ' ', 20);
	pVal[20] = 0;

}
void Spw_SamRH71_Rtems_Conf_T_Initialize(Spw_SamRH71_Rtems_Conf_T* pVal)
{
	(void)pVal;


	/*set devname */
	Spw_SamRH71_Rtems_Conf_T_devname_Initialize(pVal->devname);
	/*set nodeaddr */
	Spw_SamRH71_Rtems_Conf_Node_Addr_T_Initialize((&(pVal->nodeaddr)));
	/*set corefreq */
	pVal->exist.corefreq = 1;
	Spw_SamRH71_Rtems_Conf_Core_Frequence_T_Initialize((&(pVal->corefreq)));
	/*set clockdiv */
	pVal->exist.clockdiv = 1;
	Spw_SamRH71_Rtems_Conf_Clock_Division_T_Initialize((&(pVal->clockdiv)));
	/*set use_router */
	pVal->exist.use_router = 1;
	pVal->use_router = FALSE;
	/*set remove_prot_id */
	pVal->exist.remove_prot_id = 1;
	pVal->remove_prot_id = FALSE;
	/*set rxblock */
	pVal->exist.rxblock = 1;
	pVal->rxblock = FALSE;
	/*set txblock */
	pVal->exist.txblock = 1;
	pVal->txblock = FALSE;
}


