/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "samrh71-rtems-spw-driver.h"

flag Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Link_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((((*(pVal)) == spw0)) || (((*(pVal)) == spw1)));
	*pErrCode = ret ? 0 : ERR_SPW_SAMRH71_RTEMS_CONF_LINK_T;

	return ret;
}

#ifdef __cplusplus
const Spw_SamRH71_Rtems_Conf_Link_T Spw_SamRH71_Rtems_Conf_Link_T_constant =
	spw0;
#endif

void Spw_SamRH71_Rtems_Conf_Link_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Link_T *pVal)
{
	(void)pVal;

	(*(pVal)) = (Spw_SamRH71_Rtems_Conf_Link_T)
		Spw_SamRH71_Rtems_Conf_Link_T_constant;
}

flag Spw_SamRH71_Rtems_Conf_Node_Id_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Node_Id_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((32UL <= (*(pVal))) && ((*(pVal)) <= 255UL));
	*pErrCode = ret ? 0 : ERR_SPW_SAMRH71_RTEMS_CONF_NODE_ID_T;

	return ret;
}

#ifdef __cplusplus
const Spw_SamRH71_Rtems_Conf_Node_Id_T
	Spw_SamRH71_Rtems_Conf_Node_Id_T_constant = 32UL;
#endif

void Spw_SamRH71_Rtems_Conf_Node_Id_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Node_Id_T *pVal)
{
	(void)pVal;

	(*(pVal)) = (Spw_SamRH71_Rtems_Conf_Node_Id_T)
		Spw_SamRH71_Rtems_Conf_Node_Id_T_constant;
}

flag Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_Link_Speed_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((((((((*(pVal)) == b2Mbit)) || (((*(pVal)) == b8Mbit)))) ||
		 (((*(pVal)) == b12Mbit)))) ||
	       (((*(pVal)) == b24Mbit)));
	*pErrCode = ret ? 0 : ERR_SPW_SAMRH71_RTEMS_CONF_LINK_SPEED_T;

	return ret;
}

#ifdef __cplusplus
const Spw_SamRH71_Rtems_Conf_Link_Speed_T
	Spw_SamRH71_Rtems_Conf_Link_Speed_T_constant = b2Mbit;
#endif

void Spw_SamRH71_Rtems_Conf_Link_Speed_T_Initialize(
	Spw_SamRH71_Rtems_Conf_Link_Speed_T *pVal)
{
	(void)pVal;

	(*(pVal)) = (Spw_SamRH71_Rtems_Conf_Link_Speed_T)
		Spw_SamRH71_Rtems_Conf_Link_Speed_T_constant;
}

flag Spw_SamRH71_Rtems_Conf_T_IsConstraintValid(
	const Spw_SamRH71_Rtems_Conf_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid(
		(&(pVal->link_id)), pErrCode);
	if (ret) {
		ret = Spw_SamRH71_Rtems_Conf_Node_Id_T_IsConstraintValid(
			(&(pVal->node_id)), pErrCode);
		if (ret) {
			if (pVal->exist.link_speed) {
				ret = Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid(
					(&(pVal->link_speed)), pErrCode);
			}
		} /*COVERAGE_IGNORE*/
	} /*COVERAGE_IGNORE*/

	return ret;
}

#ifdef __cplusplus
const Spw_SamRH71_Rtems_Conf_T Spw_SamRH71_Rtems_Conf_T_constant = {
	.link_id = spw0,
	.node_id = 32UL,
	.link_speed = b2Mbit,
	.remove_prot_id = FALSE,
	.exist = { .link_speed = 1, .remove_prot_id = 1 }
};
#endif

void Spw_SamRH71_Rtems_Conf_T_Initialize(Spw_SamRH71_Rtems_Conf_T *pVal)
{
	(void)pVal;

	(*(pVal)) = (Spw_SamRH71_Rtems_Conf_T)Spw_SamRH71_Rtems_Conf_T_constant;
}
