/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "samrh71-rtems-spw-driver.h"


flag Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Link_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == spw0)) || (((*(pVal)) == spw1)));
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_LINK_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Link_T_Initialize(Spw_SamRH71_Rtems_Conf_Link_T* pVal)
{
	(void)pVal;


	(*(pVal)) = spw0;
}


flag Spw_SamRH71_Rtems_Conf_Node_Id_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Node_Id_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((32UL <= (*(pVal))) && ((*(pVal)) <= 255UL));
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_NODE_ID_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Node_Id_T_Initialize(Spw_SamRH71_Rtems_Conf_Node_Id_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 32UL;
}


flag Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Link_Speed_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((*(pVal)) == b2Mbit)) || (((*(pVal)) == b10Mbit)))) || (((*(pVal)) == b50Mbit)))) || (((*(pVal)) == b100Mbit)));
    *pErrCode = ret ? 0 :  ERR_SPW_SAMRH71_RTEMS_CONF_LINK_SPEED_T;

	return ret;
}

void Spw_SamRH71_Rtems_Conf_Link_Speed_T_Initialize(Spw_SamRH71_Rtems_Conf_Link_Speed_T* pVal)
{
	(void)pVal;


	(*(pVal)) = b2Mbit;
}


flag Spw_SamRH71_Rtems_Conf_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid((&(pVal->link_id)), pErrCode);
    if (ret) {
        ret = Spw_SamRH71_Rtems_Conf_Node_Id_T_IsConstraintValid((&(pVal->node_id)), pErrCode);
        if (ret) {
            if (pVal->exist.link_speed) {
            	ret = Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid((&(pVal->link_speed)), pErrCode);
            }
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Spw_SamRH71_Rtems_Conf_T_Initialize(Spw_SamRH71_Rtems_Conf_T* pVal)
{
	(void)pVal;


	/*set link_id */
	Spw_SamRH71_Rtems_Conf_Link_T_Initialize((&(pVal->link_id)));
	/*set node_id */
	Spw_SamRH71_Rtems_Conf_Node_Id_T_Initialize((&(pVal->node_id)));
	/*set link_speed */
	pVal->exist.link_speed = 1;
	Spw_SamRH71_Rtems_Conf_Link_Speed_T_Initialize((&(pVal->link_speed)));
	/*set remove_prot_id */
	pVal->exist.remove_prot_id = 1;
	pVal->remove_prot_id = FALSE;
}


