#ifndef GENERATED_ASN1SCC_samrh71_rtems_spw_driver_H
#define GENERATED_ASN1SCC_samrh71_rtems_spw_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef enum {
    spw0 = 0,
    spw1 = 1
} Spw_SamRH71_Rtems_Conf_Link_T;

// please use the following macros to avoid breaking code.
#define Spw_SamRH71_Rtems_Conf_Link_T_spw0 spw0
#define Spw_SamRH71_Rtems_Conf_Link_T_spw1 spw1

#define ERR_SPW_SAMRH71_RTEMS_CONF_LINK_T		276  /*spw0 | spw1*/
flag Spw_SamRH71_Rtems_Conf_Link_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Link_T* pVal, int* pErrCode);

void Spw_SamRH71_Rtems_Conf_Link_T_Initialize(Spw_SamRH71_Rtems_Conf_Link_T* pVal);
typedef asn1SccUint Spw_SamRH71_Rtems_Conf_Node_Id_T;


#define ERR_SPW_SAMRH71_RTEMS_CONF_NODE_ID_T		281  /*(32 .. 255)*/
flag Spw_SamRH71_Rtems_Conf_Node_Id_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Node_Id_T* pVal, int* pErrCode);

void Spw_SamRH71_Rtems_Conf_Node_Id_T_Initialize(Spw_SamRH71_Rtems_Conf_Node_Id_T* pVal);
typedef enum {
    b2Mbit = 2,
    b10Mbit = 10,
    b50Mbit = 50,
    b100Mbit = 100
} Spw_SamRH71_Rtems_Conf_Link_Speed_T;

// please use the following macros to avoid breaking code.
#define Spw_SamRH71_Rtems_Conf_Link_Speed_T_b2Mbit b2Mbit
#define Spw_SamRH71_Rtems_Conf_Link_Speed_T_b10Mbit b10Mbit
#define Spw_SamRH71_Rtems_Conf_Link_Speed_T_b50Mbit b50Mbit
#define Spw_SamRH71_Rtems_Conf_Link_Speed_T_b100Mbit b100Mbit

#define ERR_SPW_SAMRH71_RTEMS_CONF_LINK_SPEED_T		286  /*b2Mbit | b10Mbit | b50Mbit | b100Mbit*/
flag Spw_SamRH71_Rtems_Conf_Link_Speed_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_Link_Speed_T* pVal, int* pErrCode);

void Spw_SamRH71_Rtems_Conf_Link_Speed_T_Initialize(Spw_SamRH71_Rtems_Conf_Link_Speed_T* pVal);
/*-- Spw_SamRH71_Rtems_Conf_T --------------------------------------------*/
typedef struct {
    unsigned long link_speed:1;
    unsigned long remove_prot_id:1;
} Spw_SamRH71_Rtems_Conf_T_exist;
typedef struct {
    Spw_SamRH71_Rtems_Conf_Link_T link_id;
    Spw_SamRH71_Rtems_Conf_Node_Id_T node_id;
    Spw_SamRH71_Rtems_Conf_Link_Speed_T link_speed;
    flag remove_prot_id;

    Spw_SamRH71_Rtems_Conf_T_exist exist;

} Spw_SamRH71_Rtems_Conf_T;

#define ERR_SPW_SAMRH71_RTEMS_CONF_T		326  /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_LINK_ID_2		296  /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_NODE_ID_2		306  /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_LINK_SPEED_2		316  /**/
#define ERR_SPW_SAMRH71_RTEMS_CONF_T_REMOVE_PROT_ID		321  /**/
flag Spw_SamRH71_Rtems_Conf_T_IsConstraintValid(const Spw_SamRH71_Rtems_Conf_T* pVal, int* pErrCode);

void Spw_SamRH71_Rtems_Conf_T_Initialize(Spw_SamRH71_Rtems_Conf_T* pVal);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
